"""GLM trade-suggestion layer (P3 decision layer).

Turns the latest 15-day forecast path per stock (operational Google Sheet),
the latest FinBERT sentiment snapshot (Firestore ``sentiment_latest``), and
the recent quarterly fundamentals (Firestore ``fundamentals``) into a
BUY / HOLD / AVOID suggestion with sell timing and a stop-loss, generated by
GLM (OpenAI-compatible endpoint, e.g. Ollama Cloud glm-4.7) and stored in
Firestore collection ``trade_suggestions`` (one doc per ticker).

Incremental contract ("contextualize once, then only new data"):
every suggestion doc stores an ``input_fingerprint`` — a sha256 of the
forecast path + sentiment snapshot + fundamentals it was generated from. On
later runs a stock is re-sent to the LLM only when that fingerprint changes
(or --force).

Environment:
    GLM_API_KEY   — API key (required)
    GLM_BASE_URL  — OpenAI-compatible base URL (default https://ollama.com/v1)
    GLM_MODEL     — model id (default glm-4.7)
    SHEET_ID / OPERATIONAL_SHEET_ID — operational Google Sheet
    FIREBASE_CREDENTIALS — Firestore service account (see ingestion/_firestore)

Usage:
    python -m features.trade_suggestions                   # all worksheets
    python -m features.trade_suggestions --tickers RELIANCE,TCS
    python -m features.trade_suggestions --dry-run         # no Firestore write
    python -m features.trade_suggestions --force           # ignore fingerprints
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

import requests

from ingestion._firestore import init_firestore_client
from ingestion.aliases import sector_for
from ingestion.sectors import sector_entity_id

# Load .env so standalone runs (python -m ...) see the same configuration as
# Docker / collect_all. Existing environment variables always win.
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

DEFAULT_SHEET_ID = (
    os.environ.get("OPERATIONAL_SHEET_ID")
    or os.environ.get("SHEET_ID")
    or "1uekPHyvJj4p6YjxNwlBBIAI71SWRye-xxFu47Kgpf9o"
)
GLM_BASE_URL = os.environ.get("GLM_BASE_URL", "https://ollama.com/v1").rstrip("/")
GLM_MODEL = os.environ.get("GLM_MODEL", "glm-4.7")

SENTIMENT_COLLECTION = os.environ.get("SENTIMENT_FIRESTORE_COLLECTION", "sentiment_latest")
SUGGESTIONS_COLLECTION = os.environ.get("SUGGESTIONS_FIRESTORE_COLLECTION", "trade_suggestions")
FUNDAMENTALS_COLLECTION = os.environ.get("FUNDAMENTALS_FIRESTORE_COLLECTION", "fundamentals")
FUNDAMENTALS_QUARTERS = 5  # latest N quarters handed to the LLM for trend context
                           # (rolling window: oldest drops off as a new quarter arrives)

# Suggestion-doc schema version so downstream readers can detect the payload
# shape. v1 = forecast + sentiment only; v2 = adds fundamentals context and the
# sentiment_used / fundamentals_used provenance flags; v3 = sentiment is now
# split into the company's own + its sector's + GENERAL (other companies'/
# sectors' sentiment is never sent to a given stock).
SUGGESTION_SCHEMA_VERSION = 3

GENERAL_ENTITY = "GENERAL"

FORECAST_COLS = [f"Forecast_Close_T+{h}" for h in range(1, 16)]
RECENT_CLOSES = 5           # trailing closes given to the LLM as context
BATCH_GET_CHUNK = 20        # worksheets per Sheets values_batch_get call
LLM_TIMEOUT_SECONDS = 240
LLM_RETRIES = 5
MIN_REQUEST_INTERVAL = float(os.environ.get("GLM_MIN_REQUEST_INTERVAL", "3.0"))

# Global pacing so concurrent workers don't burst past the API rate limit:
# request starts are spaced at least MIN_REQUEST_INTERVAL seconds apart.
_throttle_lock = threading.Lock()
_next_slot = [0.0]


def _throttle() -> None:
    with _throttle_lock:
        now = time.monotonic()
        wait = max(0.0, _next_slot[0] - now)
        _next_slot[0] = max(now, _next_slot[0]) + MIN_REQUEST_INTERVAL
    if wait:
        time.sleep(wait)

SYSTEM_PROMPT = (
    "You are a disciplined equity trading assistant for NSE (India) stocks. "
    "You are given a stock's recent closing prices, a model-generated 15-day "
    "forecast path of closing prices, (when available) news sentiment split into "
    "three buckets — the company's own, its SECTOR's, and GENERAL market — and "
    "(when available) recent quarterly fundamentals (revenue, margins, ROE, "
    "leverage, cash flow across the last few quarters). Weigh all of these: the "
    "forecast path drives timing/price levels; company sentiment matters most, "
    "then its sector, then general market tone; fundamentals adjust conviction — "
    "deteriorating fundamentals or negative company/sector sentiment should lower "
    "confidence or push toward HOLD/AVOID even on a favourable forecast. "
    "Respond with a single JSON object and nothing else, using "
    "exactly these keys:\n"
    '  "action": "BUY" | "HOLD" | "AVOID",\n'
    '  "buy_price": number or null (suggested entry, INR),\n'
    '  "sell_day": string (e.g. "T+7") or null,\n'
    '  "sell_price": number or null (target exit, INR),\n'
    '  "stoploss": number (protective stop, INR),\n'
    '  "confidence": number between 0 and 1,\n'
    '  "rationale": string (2-3 sentences, mention forecast trend, expected '
    "return vs risk, and sentiment if available).\n"
    "Be conservative: recommend BUY only when the forecast path shows a "
    "clear favourable risk/reward; place the stop-loss below recent support "
    "or ~2-4% under entry, whichever is tighter."
)


def _log(msg: str) -> None:
    print(msg, flush=True)


# ---------------------------------------------------------------------------
# Google Sheet — latest forecast path per worksheet
# ---------------------------------------------------------------------------

def load_forecasts(sheet_id: str, tickers: Optional[List[str]] = None) -> Dict[str, Dict[str, Any]]:
    """Return {ticker: {date, close, recent_closes, forecast: {T+1: px, ...}}}.

    Reads worksheets in batched value ranges to stay inside the Sheets
    read-quota (5 batch calls instead of ~98 per-worksheet reads).
    """
    from utils.google_auth import get_gspread_client

    client = get_gspread_client()
    spreadsheet = client.open_by_key(sheet_id)
    titles = [ws.title for ws in spreadsheet.worksheets()]
    if tickers:
        wanted = {t.strip().upper() for t in tickers}
        titles = [t for t in titles if t.upper() in wanted]

    out: Dict[str, Dict[str, Any]] = {}
    for start in range(0, len(titles), BATCH_GET_CHUNK):
        chunk = titles[start:start + BATCH_GET_CHUNK]
        ranges = [f"'{title}'" for title in chunk]
        response = spreadsheet.values_batch_get(ranges)
        for title, vr in zip(chunk, response.get("valueRanges", [])):
            parsed = _parse_worksheet(vr.get("values", []))
            if parsed is not None:
                out[title] = parsed
            else:
                _log(f"[suggest] {title}: no usable forecast row — skipped")
    return out


def _parse_worksheet(values: List[List[str]]) -> Optional[Dict[str, Any]]:
    if not values or len(values) < 2:
        return None
    header = values[0]
    col = {name: idx for idx, name in enumerate(header)}
    if "Close" not in col or FORECAST_COLS[0] not in col:
        return None

    def cell(row: List[str], name: str) -> Optional[str]:
        idx = col.get(name)
        if idx is None or idx >= len(row):
            return None
        return row[idx] if row[idx] != "" else None

    def as_float(raw: Optional[str]) -> Optional[float]:
        if raw is None:
            return None
        try:
            return float(str(raw).replace(",", ""))
        except ValueError:
            return None

    # Latest row that has both a Close and a T+1 forecast.
    latest = None
    closes: List[float] = []
    for row in values[1:]:
        close = as_float(cell(row, "Close"))
        if close is not None:
            closes.append(close)
            if as_float(cell(row, FORECAST_COLS[0])) is not None:
                latest = row
    if latest is None:
        return None

    forecast = {}
    for name in FORECAST_COLS:
        px = as_float(cell(latest, name))
        if px is not None:
            forecast[name.replace("Forecast_Close_", "")] = px
    if not forecast:
        return None

    return {
        "date": cell(latest, "Date"),
        "close": as_float(cell(latest, "Close")),
        "recent_closes": closes[-RECENT_CLOSES:],
        "forecast": forecast,
    }


# ---------------------------------------------------------------------------
# Firestore — sentiment in, suggestions out
# ---------------------------------------------------------------------------

def load_sentiment(client: Any) -> Dict[str, List[Dict[str, Any]]]:
    """Return {ticker: [snapshot per source]} from ``sentiment_latest``."""
    out: Dict[str, List[Dict[str, Any]]] = {}
    for doc in client.collection(SENTIMENT_COLLECTION).stream():
        data = doc.to_dict() or {}
        ticker = data.get("ticker")
        if ticker:
            out.setdefault(ticker, []).append(
                {
                    k: data.get(k)
                    for k in (
                        "source", "as_of_date", "sent_mean_3d", "sent_mean_7d",
                        "sent_pos_share", "sent_neg_share", "n_3d", "n_7d",
                    )
                }
            )
    return out


def sentiment_context_for(ticker: str, sentiment: Dict[str, List[Dict[str, Any]]]) -> Dict[str, Any]:
    """Assemble the sentiment a single stock is allowed to see.

    Returns the company's own sentiment, its sector's sentiment, and the GENERAL
    macro sentiment — and nothing else. Other companies' and other sectors'
    sentiment is deliberately excluded so the LLM only weighs signals relevant
    to this stock.
    """
    sector = sector_for(ticker)
    sector_entity = sector_entity_id(sector) if sector and sector != "Unknown" else None
    return {
        "company": sentiment.get(ticker),
        "sector": {
            "name": sector,
            "sentiment": sentiment.get(sector_entity) if sector_entity else None,
        },
        "general": sentiment.get(GENERAL_ENTITY),
    }


def _has_sentiment(context: Dict[str, Any]) -> bool:
    return bool(
        context.get("company")
        or (context.get("sector") or {}).get("sentiment")
        or context.get("general")
    )


def load_fundamentals(client: Any) -> Dict[str, Dict[str, Any]]:
    """Return {ticker: compact fundamentals summary} from ``fundamentals``.

    Reads the per-ticker fundamentals docs written by
    :mod:`ingestion.fundamentals` (``quarters`` keyed by ``YYYYQn``) and keeps
    only the latest ``FUNDAMENTALS_QUARTERS`` quarters, most-recent first, so
    the LLM sees the current fundamentals plus enough history to judge trend.
    """
    out: Dict[str, Dict[str, Any]] = {}
    for doc in client.collection(FUNDAMENTALS_COLLECTION).stream():
        data = doc.to_dict() or {}
        ticker = data.get("ticker") or doc.id
        quarters = data.get("quarters") or {}
        if not ticker or not isinstance(quarters, dict) or not quarters:
            continue
        # Order quarters newest-first by their period-end date (fall back to the
        # quarter label so ordering is stable even if a date is missing).
        ordered = sorted(
            quarters.items(),
            key=lambda kv: (str((kv[1] or {}).get("quarter_end_date") or ""), kv[0]),
            reverse=True,
        )[:FUNDAMENTALS_QUARTERS]
        recent = {
            q: {
                "quarter_end_date": (payload or {}).get("quarter_end_date"),
                "financials": (payload or {}).get("financials") or {},
            }
            for q, payload in ordered
        }
        out[str(ticker).upper()] = {
            "scrape_date": data.get("scrape_date"),
            "latest_quarter": ordered[0][0] if ordered else None,
            "recent_quarters": recent,
        }
    return out


def load_existing_fingerprints(client: Any) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for doc in client.collection(SUGGESTIONS_COLLECTION).stream():
        data = doc.to_dict() or {}
        if data.get("input_fingerprint"):
            out[doc.id] = data["input_fingerprint"]
    return out


def fingerprint(payload: Dict[str, Any]) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, default=str).encode()
    ).hexdigest()


# ---------------------------------------------------------------------------
# GLM call
# ---------------------------------------------------------------------------

def _positive_number(value: Any) -> Optional[float]:
    """Return ``value`` as a positive float, or ``None`` if absent/invalid."""
    try:
        f = float(value)
    except (TypeError, ValueError):
        return None
    return f if f == f and f > 0 else None


def _extract_json(text: str) -> Dict[str, Any]:
    """Parse the first JSON object out of an LLM reply (tolerates fences)."""
    text = re.sub(r"^```(?:json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end <= start:
        raise ValueError(f"no JSON object in LLM reply: {text[:160]!r}")
    return json.loads(text[start:end + 1])


def ask_glm(ticker: str, market: Dict[str, Any], sentiment: Optional[Dict[str, Any]],
            model: str, api_key: str,
            fundamentals: Optional[Dict[str, Any]] = None,
            *, base_url: Optional[str] = None,
            max_attempts: Optional[int] = None) -> Dict[str, Any]:
    """Ask an OpenAI-compatible LLM for a BUY/HOLD/AVOID suggestion.

    ``base_url`` overrides the module default (``GLM_BASE_URL``) so a caller can
    hit a different provider (e.g. Groq) with the same code. ``max_attempts``
    overrides ``LLM_RETRIES`` — the backtest's key-rotation client sets it to 1
    so a failing key rotates immediately instead of burning all local retries.
    """
    url_base = (base_url or GLM_BASE_URL).rstrip("/")
    retries = max_attempts if max_attempts is not None else LLM_RETRIES
    if isinstance(sentiment, dict):
        news_sentiment: Any = sentiment if _has_sentiment(sentiment) else "unavailable"
    else:
        news_sentiment = sentiment or "unavailable"
    user_prompt = json.dumps(
        {
            "ticker": ticker,
            "as_of_date": market.get("date"),
            "last_close_inr": market.get("close"),
            f"previous_{RECENT_CLOSES}_closes": market.get("recent_closes"),
            "forecast_path_inr": market.get("forecast"),
            "news_sentiment": news_sentiment,
            "fundamentals": fundamentals or "unavailable",
        },
        default=str,
    )
    last_exc: Optional[Exception] = None
    for attempt in range(1, retries + 1):
        try:
            _throttle()
            resp = requests.post(
                f"{url_base}/chat/completions",
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": model,
                    "temperature": 0.2,
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                },
                timeout=LLM_TIMEOUT_SECONDS,
            )
            if resp.status_code == 429:
                # Honor the server's Retry-After when present; otherwise back
                # off hard — rate windows on Ollama Cloud are tens of seconds.
                retry_after = float(resp.headers.get("retry-after") or 0)
                wait = max(retry_after, 20.0 * attempt)
                raise RuntimeError(f"429 rate-limited (waiting {wait:.0f}s)")
            resp.raise_for_status()
            content = resp.json()["choices"][0]["message"]["content"]
            suggestion = _extract_json(content)
            if suggestion.get("action") not in ("BUY", "HOLD", "AVOID"):
                raise ValueError(f"invalid action: {suggestion.get('action')!r}")
            # A BUY must carry the exit plan the trading layer relies on: a target
            # (sell_price) and a protective stoploss. Enforce it so a BUY is always
            # actionable — missing either triggers a retry rather than a naked BUY.
            if suggestion.get("action") == "BUY":
                if _positive_number(suggestion.get("sell_price")) is None:
                    raise ValueError("BUY missing target price (sell_price)")
                if _positive_number(suggestion.get("stoploss")) is None:
                    raise ValueError("BUY missing stoploss")
            return suggestion
        except Exception as exc:  # noqa: BLE001 — retried, surfaced on final failure
            last_exc = exc
            if attempt < retries:
                wait = 20.0 * attempt if "429" in str(exc) else 3.0 * attempt
                time.sleep(wait)
    raise RuntimeError(f"GLM call failed after {retries} attempts: {last_exc}")


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def run(argv: Optional[List[str]] = None) -> Dict[str, Any]:
    parser = argparse.ArgumentParser(
        prog="trade_suggestions",
        description="GLM buy/sell/stop-loss suggestions from forecasts + sentiment.",
    )
    parser.add_argument("--sheet-id", default=DEFAULT_SHEET_ID)
    parser.add_argument("--tickers", default=None, help="Comma-separated subset (default: all worksheets).")
    parser.add_argument("--model", default=GLM_MODEL)
    parser.add_argument("--workers", type=int, default=4, help="Concurrent LLM calls (default 4).")
    parser.add_argument("--limit", type=int, default=None, help="Cap number of stocks sent to the LLM this run.")
    parser.add_argument("--force", action="store_true", help="Re-generate even when inputs are unchanged.")
    parser.add_argument("--dry-run", action="store_true", help="Print suggestions without writing Firestore.")
    args = parser.parse_args(argv)

    api_key = os.environ.get("GLM_API_KEY")
    if not api_key:
        _log("[suggest] GLM_API_KEY is not set — aborting")
        return {"error": "GLM_API_KEY not set"}

    tickers = [t.strip() for t in args.tickers.split(",")] if args.tickers else None
    _log(f"[suggest] loading forecasts from sheet {args.sheet_id} …")
    forecasts = load_forecasts(args.sheet_id, tickers)
    _log(f"[suggest] {len(forecasts)} worksheets with a usable forecast path")

    fs = init_firestore_client()
    sentiment = load_sentiment(fs)
    fundamentals = load_fundamentals(fs)
    _log(f"[suggest] loaded fundamentals for {len(fundamentals)} tickers")
    existing = {} if args.force else load_existing_fingerprints(fs)

    todo: List[Tuple[str, Dict[str, Any], Dict[str, Any], Optional[Dict[str, Any]], str]] = []
    skipped_unchanged = 0
    for ticker in sorted(forecasts):
        market = forecasts[ticker]
        snap = sentiment_context_for(ticker, sentiment)
        fund = fundamentals.get(ticker.upper())
        fp = fingerprint({"market": market, "sentiment": snap, "fundamentals": fund})
        if existing.get(ticker) == fp:
            skipped_unchanged += 1
            continue
        todo.append((ticker, market, snap, fund, fp))
    if args.limit is not None:
        todo = todo[: args.limit]
    _log(f"[suggest] {len(todo)} stocks need suggestions "
         f"({skipped_unchanged} unchanged, skipped)")

    written = failed = 0
    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
        futures = {
            pool.submit(ask_glm, ticker, market, snap, args.model, api_key, fund):
                (ticker, market, snap, fund, fp)
            for ticker, market, snap, fund, fp in todo
        }
        for future in as_completed(futures):
            ticker, market, snap, fund, fp = futures[future]
            try:
                suggestion = future.result()
            except Exception as exc:  # noqa: BLE001 — per-stock isolation
                failed += 1
                _log(f"[suggest] {ticker}: FAILED — {exc}")
                continue
            doc = {
                "ticker": ticker,
                "schema_version": SUGGESTION_SCHEMA_VERSION,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "model": args.model,
                "as_of_date": market.get("date"),
                "last_close_inr": market.get("close"),
                "sentiment_used": _has_sentiment(snap),
                "fundamentals_used": bool(fund),
                "input_fingerprint": fp,
                **{k: suggestion.get(k) for k in
                   ("action", "buy_price", "sell_day", "sell_price",
                    "stoploss", "confidence", "rationale")},
            }
            if args.dry_run:
                _log(f"[suggest] {ticker} (dry-run): {json.dumps(doc, default=str)}")
            else:
                fs.collection(SUGGESTIONS_COLLECTION).document(ticker).set(doc)
                _log(f"[suggest] {ticker}: {doc['action']} "
                     f"(sell {doc.get('sell_day')}, stop {doc.get('stoploss')}) — stored")
            written += 1

    summary = {
        "suggested": written,
        "skipped_unchanged": skipped_unchanged,
        "failed": failed,
        "collection": SUGGESTIONS_COLLECTION,
        "dry_run": args.dry_run,
    }
    print(json.dumps(summary))
    return summary


if __name__ == "__main__":
    result = run()
    sys.exit(1 if result.get("error") or result.get("failed") else 0)
